### ISSUE TITLE
fdtd3d running low efficiency

### ISSUE THREAD

**Issue by EMinsight** [zer011b/fdtd3d#101]
I have tested meep and fdtd3d on same computer running with mpi 8 cores.

The grid is 100 100 100 and 100 time steps, The meep runnning time is about 1.5s, but fdtd3d is about 52s.

**Comment by xj361685640** [comment]
I have tested meep and fdtd3d on same computer running with mpi 8 cores.

The grid is 100*100*100 and 100 time step, The meep runnning time is about 1.5s, but fdtd3d is about 52s.

**Comment by zer011b** [comment]
Please, post build and run commands for both meep and fdtd3d

**Comment by EMinsight** [comment]
fdtd3d running command：
mpiexec -n 8 ./fdtd3d --3d --parallel-grid --time-steps 100 --sizex 100 --sizey 100 --sizez 100

fdtd3d output message:
Nodes' grid (OPTIMAL): 2x2x2.

NOTE: you use OPTIMAL virtual topology (2x2x2).
OPTIMAL virtual topology has some requirements in order for it to be optimal:
  - all computational nodes have the same performance
  - all neighbouring computational nodes have the same share time
  - virtual topology matches physical topology
In other words, OPTIMAL virtual topology is optimal only for homogeneous architectures.
Make sure all these requirements are met, otherwise, OPTIMAL virtual topology could be non-optimal.

Total time = 244.675675 seconds
Dimension: 3
Grid size: 100x100x100
Number of time steps: 100

Value type: double
Number of time steps: 2

-------- Details --------
Parallel grid: 1
Number of processes: 8
Parallel grid scheme: XYZ
Buffer size: 1


meep test_script
(set! geometry-lattice (make lattice (size 10 10 10)))
(set! resolution 10)
(run-until 100)

meep running command:
mpiexec -n 8 ./meep-mpi test_script

meep output message:
Using MPI version 3.0, 8 processes

Initializing structure...
Working in 3D dimensions.
Computational cell is 10 x 10 x 10 with resolution 10
time for set_epsilon = 1.85122 s

Meep progress: 0.6000000000000001/100.0 = 0.6% done in 4.1s, 678.6s to go
on time step 12 (time=0.6), 0.341444 s/step
Meep progress: 1.4000000000000001/100.0 = 1.4% done in 8.3s, 583.4s to go
on time step 28 (time=1.4), 0.261693 s/step
Meep progress: 2.1/100.0 = 2.1% done in 12.3s, 574.6s to go
on time step 42 (time=2.1), 0.288639 s/step
Meep progress: 2.75/100.0 = 2.8% done in 16.5s, 585.0s to go
on time step 55 (time=2.75), 0.324534 s/step
Meep progress: 3.45/100.0 = 3.4% done in 20.9s, 585.6s to go
on time step 69 (time=3.45), 0.312974 s/step
Meep progress: 91.65/100.0 = 91.6% done in 25.0s, 2.3s to go
on time step 1833 (time=91.65), 0.00230164 s/step
run 0 finished at t = 100.0 (2000 timesteps)

Elapsed run time = 27.9844 s

**Comment by zer011b** [comment]
Future release will improve performance of fdtd3d. Also, meep relies on symmetry, which is currently only in far future plans for fdtd3d
