### ISSUE TITLE
Hello, I have a Problem.

### ISSUE THREAD

**Issue by wookhyun6165** [zer011b/fdtd3d#137]
Hi, I'm wookhyun.
I wanted to use your public fdtd3d source code.
However, The following problems have occurred:
 @@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

[ 66%] Built target fdtd3d
[ 69%] Built target fdtd3d-convert
[ 71%] Built target unit-test-internalscheme
[ 74%] Built target unit-test-complex
[ 76%] Building CXX object Tests/CMakeFiles/unit-test-approximation.dir/unit-test-approximation.cpp.o
/home/awh/fdtd3d/Tests/unit-test-approximation.cpp:11:2: error: #error Test requires debug info
 #error Test requires debug info
  ^~~~~
Tests/CMakeFiles/unit-test-approximation.dir/build.make:62: recipe for target 'Tests/CMakeFiles/unit-test-approximation.dir/unit-test-approximation.cpp.o' failed
make[2]: *** [Tests/CMakeFiles/unit-test-approximation.dir/unit-test-approximation.cpp.o] Error 1
CMakeFiles/Makefile2:1036: recipe for target 'Tests/CMakeFiles/unit-test-approximation.dir/all' failed
make[1]: *** [Tests/CMakeFiles/unit-test-approximation.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

I've tried a lot of ways, but it hasn't been solved.
Your help is desperately required.

**Comment by zer011b** [comment]
Simple `make` command will try to build all targets, and `unit-test-approximation` is not supported in release mode, for example. So you should use `make fdtd3d`.

Please, share build commands, which you've used.

**Comment by wookhyun6165** [comment]
Oh, Thanks for your kind reply.
1.
I started to type the command as bellow :

%%%%%%%%%%%%%%%%%%%%%%%%%%%
mkdir Release
cd Release
cmake .. -DCMAKE_BUILD_TYPE=Release
make
%%%%%%%%%%%%%%%%%%%%%%%%%%%

As a result, I found that ans error occurred and The reason is release mode.


2.
I have another question about Prerequisites.
I typed the command as bellow :

%%%%%%%%%%%%%%%%%%%%%%%%%%%
./install-cmake.sh
export PATH=`pwd`/Third-party/cmake/bin:$PATH
%%%%%%%%%%%%%%%%%%%%%%%%%%%

Then, I got an error message like this : 

%%%%%%%%%%%%%%%%%%%%%%%%%%%
+ git clone https://gitlab.kitware.com/cmake/cmake.git /Third-party/cmake
fatal: The destination path('/Third-party/cmake') already exists and is not an empty directory.
%%%%%%%%%%%%%%%%%%%%%%%%%%%


3.
Finally, I'd like to simulate 'sphere.txt' in "./Examples".
How can i proceed and get results?

I'm so sorry to bother you so much.
Since I'm a beginner of Github and Linux, i need your help.
Thank you for reading my  @issue.
Have a good day ~ !

**Comment by zer011b** [comment]
1. Example is not correct in this sense, it is very general. You can configure many parameters with `cmake` to be specific for your needs, see https://github.com/zer011b/fdtd3d/blob/master/Docs/Build.md. Then, invoke:
```
make fdtd3d
````

2. You do not need to build cmake manually, if there are binaries shipped for your OS (see https://cmake.org/download/).

3. Launch is described in https://github.com/zer011b/fdtd3d/blob/master/Docs/Launch.md. Basically, you'll need to invoke:
```
./Release/Source/fdtd3d --cmd-from-file ./Examples/sphere.txt
```

On how to get output, see https://github.com/zer011b/fdtd3d/blob/master/Docs/Input-Output.md.
