### ISSUE TITLE
Is fdtd3d suitable for antenna design?

### ISSUE THREAD

**Issue by 0xCoto** [zer011b/fdtd3d#171]
Hi, quick question: would this library be at all suitable for antenna design, or is the FDTD implementation primarily intended for different applications?

**Comment by zer011b** [comment]
I do not have any experience related to antenna design, but you can specify your own geometry and pass `.txt` file as input to fdtd3d using `--load-eps-from-file <path_to_file.txt>` and similar options (see https://github.com/zer011b/fdtd3d/blob/master/Docs/Input-Output.md). Then FDTD simulation will be performed with this geometry.
