### ISSUE TITLE
FDTD for metals

### ISSUE THREAD

**Issue by leSemaleon** [zer011b/fdtd3d#189]
Hello,
Have This project support for complex and negative permittivity?

**Comment by zer011b** [comment]
Yes, for dispersive materials fdtd3d supports Drude model. See `--load-omegape-from-file`, `--load-omegapm-from-file`, `--load-gammae-from-file` and `--load-gammam-from-file` in help, as well as https://github.com/zer011b/fdtd3d/blob/master/Docs/Input-Output.md for how to use input files.
