### ISSUE TITLE
building failed

### ISSUE THREAD

**Issue by EMinsight** [zer011b/fdtd3d#72]
Here is the error message

[  3%] Built target EasyBMP
[  6%] Built target Helpers
[ 23%] Built target FM
[ 26%] Built target Loader
[ 30%] Built target Coordinate
[ 36%] Built target Dumper
[ 40%] Building CXX object Source/Layout/CMakeFiles/Layout.dir/ParallelYeeGridLayout.cpp.o
In file included from /home/cen/XJ/fdtd3d/Source/Layout/ParallelYeeGridLayout.h:4:0,
                 from /home/cen/XJ/fdtd3d/Source/Layout/ParallelYeeGridLayout.cpp:1:
/home/cen/XJ/fdtd3d/Source/Layout/YeeGridLayout.h: In member function ‘FPValue YeeGridLayout::getMetaMaterial(GridCoordinate3D&, GridType, Grid<TCoord>&, GridType, Grid<TCoord>&, GridType, Grid<TCoord>&, GridType, FPValue&, FPValue&)’:
/home/cen/XJ/fdtd3d/Source/Layout/YeeGridLayout.h:777:22: error: ambiguous overload for ‘operator*’ (operand types are ‘int’ and ‘GridCoordinate3D’)
         absPos11 = 2 * getEpsCoord (realCoord - GridCoordinateFP3D (0.5, 0, 0)) + GridCoordinate3D (1, 0, 0);
                      ^
/home/cen/XJ/fdtd3d/Source/Layout/YeeGridLayout.h:777:22: note: candidates are:
In file included from /home/cen/XJ/fdtd3d/Source/Coordinate/GridCoordinate2D.h:4:0,
                 from /home/cen/XJ/fdtd3d/Source/Coordinate/GridCoordinate3D.h:4,
                 from /home/cen/XJ/fdtd3d/Source/Layout/Approximation.h:5,
                 from /home/cen/XJ/fdtd3d/Source/Layout/YeeGridLayout.h:4,
                 from /home/cen/XJ/fdtd3d/Source/Layout/ParallelYeeGridLayout.h:4,
                 from /home/cen/XJ/fdtd3d/Source/Layout/ParallelYeeGridLayout.cpp:1:
/home/cen/XJ/fdtd3d/Source/Coordinate/GridCoordinate1D.h:99:57: note: GridCoordinate1DTemplate<TcoordType> operator*(FPValue, const GridCoordinate1DTemplate<TCoord>&) [with TCoord = long unsigned int; TcoordType = long unsigned int; FPValue = double]
   friend GridCoordinate1DTemplate CUDA_DEVICE CUDA_HOST operator* (FPValue lhs, const GridCoordinate1DTemplate<TCoord>& rhs)
                                                         ^
In file included from /home/cen/XJ/fdtd3d/Source/Coordinate/GridCoordinate3D.h:4:0,
                 from /home/cen/XJ/fdtd3d/Source/Layout/Approximation.h:5,
                 from /home/cen/XJ/fdtd3d/Source/Layout/YeeGridLayout.h:4,
                 from /home/cen/XJ/fdtd3d/Source/Layout/ParallelYeeGridLayout.h:4,
                 from /home/cen/XJ/fdtd3d/Source/Layout/ParallelYeeGridLayout.cpp:1:
/home/cen/XJ/fdtd3d/Source/Coordinate/GridCoordinate2D.h:128:57: note: GridCoordinate2DTemplate<TcoordType> operator*(FPValue, const GridCoordinate2DTemplate<TCoord>&) [with TCoord = long unsigned int; TcoordType = long unsigned int; FPValue = double]
   friend GridCoordinate2DTemplate CUDA_DEVICE CUDA_HOST operator* (FPValue lhs, const GridCoordinate2DTemplate<TCoord>& rhs)
                                                         ^
In file included from /home/cen/XJ/fdtd3d/Source/Layout/Approximation.h:5:0,
                 from /home/cen/XJ/fdtd3d/Source/Layout/YeeGridLayout.h:4,
                 from /home/cen/XJ/fdtd3d/Source/Layout/ParallelYeeGridLayout.h:4,
                 from /home/cen/XJ/fdtd3d/Source/Layout/ParallelYeeGridLayout.cpp:1:
/home/cen/XJ/fdtd3d/Source/Coordinate/GridCoordinate3D.h:169:57: note: GridCoordinate3DTemplate<TcoordType> operator*(FPValue, const GridCoordinate3DTemplate<TCoord>&) [with TCoord = long unsigned int; TcoordType = long unsigned int; FPValue = double]
   friend GridCoordinate3DTemplate CUDA_DEVICE CUDA_HOST operator* (FPValue lhs, const GridCoordinate3DTemplate<TCoord>& rhs)
                                                         ^
........................................................................................

How can I deal with it?

**Comment by zer011b** [comment]
Please, specify the build parameters, which you have used

**Comment by EMinsight** [comment]
-DCMAKE_BUILD_TYPE=Release -DVALUE_TYPE=d -DCOMPLEX_FIELD_VALUES=ON -DTIME_STEPS=2 -DPARALLEL_GRID_DIMENSION=3 -DPRINT_MESSAGE=OFF -DPARALLEL_GRID=ON -DPARALLEL_BUFFER_DIMENSION=xyz -DCXX11_ENABLED=ON -DCUDA_ENABLED=OFF -DCUDA_ARCH_SM_TYPE=sm_20

**Comment by EMinsight** [comment]
I have tested ubuntu 16.04, cmake file have passed well when I use the example build command for 3D grid.

After that, I make the program, It comes the information below

[  4%] Built target EasyBMP
[  9%] Built target Helpers
[ 13%] Built target Settings
[ 20%] Built target Kernels
[ 25%] Built target Coordinate
[ 46%] Built target Grid
[ 55%] Built target Layout
[ 69%] Built target FM
[ 74%] Built target Loader
[ 81%] Built target Dumper
[ 83%] Building CXX object Source/Scheme/CMakeFiles/Scheme.dir/Scheme3D.cpp.o
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp: In member function ‘void Scheme3D::performNSteps(time_step, time_step)’:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:2519:9: error: ‘dumperEx’ was not declared in this scope
         dumperEx.init (t, CURRENT, processId, "3D-in-time-total-Ex");
         ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:2522:9: error: ‘dumperEy’ was not declared in this scope
         dumperEy.init (t, CURRENT, processId, "3D-in-time-total-Ey");
         ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:2525:9: error: ‘dumperEz’ was not declared in this scope
         dumperEz.init (t, CURRENT, processId, "3D-in-time-total-Ez");
         ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:2528:9: error: ‘dumperHx’ was not declared in this scope
         dumperHx.init (t, CURRENT, processId, "3D-in-time-total-Hx");
         ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:2531:9: error: ‘dumperHy’ was not declared in this scope
         dumperHy.init (t, CURRENT, processId, "3D-in-time-total-Hy");
         ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:2534:9: error: ‘dumperHz’ was not declared in this scope
         dumperHz.init (t, CURRENT, processId, "3D-in-time-total-Hz");
         ^
Source/Scheme/CMakeFiles/Scheme.dir/build.make:110: recipe for target 'Source/Scheme/CMakeFiles/Scheme.dir/Scheme3D.cpp.o' failed
make[2]: *** [Source/Scheme/CMakeFiles/Scheme.dir/Scheme3D.cpp.o] Error 1
CMakeFiles/Makefile2:700: recipe for target 'Source/Scheme/CMakeFiles/Scheme.dir/all' failed
make[1]: *** [Source/Scheme/CMakeFiles/Scheme.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zer011b** [comment]
I'm preparing a large update, which will fix this build issue as well. Right now you can fix this by specifying -DPARALLEL_GRID=OFF

**Comment by zer011b** [comment]
Fixed
