### ISSUE TITLE
how to input build-in geometry for simulation

### ISSUE THREAD

**Issue by EMinsight** [zer011b/fdtd3d#73]
I would like to define some geometry which used in the simulation.

If you don,t have time to do it, I can help you to implement it.

Also there is a advice, we usually want to output filed value(Ex, Ey....) for post-process, the output type should have point, line, plane, volume in time domain and frequency domain.

**Comment by zer011b** [comment]
Currently, there is no way to specify geometry outside of the source code.

There are different types of dumpers/loaders already implemented, i.e. bmp, dat and txt. For example, TXTDumper saves results in the plain text format and allows to further manipulate data. Loaders allow to load geometry from files, which could by generated by third-party tools.

Command line options for using this dumpers and loaders are WIP, so when they are finished, user will be able to specify something like this `--save-as-txt` for saving results as plain text, and `--load-eps-from-txt` to loading specific geometry from plain text file.

**Comment by zer011b** [comment]
Pull request #79 implemented input of geometry from files. 

Specify `--load-eps-from-file <filename>` to load Eps from file, and `--save-res --save-as-bmp --save-as-txt` to save results to disk (filenames are default ones).

Input `.txt` files could be generated with scripts, output `.txt` files could be used for post-processing with scripts. 

See `--help` for more details.

**Comment by zer011b** [comment]
I've added additional info on input and output to Docs/Input-Output.md
