### ISSUE TITLE
building failed

### ISSUE THREAD

**Issue by EMinsight** [zer011b/fdtd3d#81]
cmake build command
cmake .. -DCMAKE_BUILD_TYPE=Release -DVALUE_TYPE=d -DCOMPLEX_FIELD_VALUES=OFF -DTIME_STEPS=2 -DPARALLEL_GRID_DIMENSION=3 -DPRINT_MESSAGE=ON -DPARALLEL_GRID=ON -DPARALLEL_BUFFER_DIMENSION=xyz -DCXX11_ENABLED=ON -DCUDA_ENABLED=OFF -DCUDA_ARCH_SM_TYPE=sm_50 -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc

[  2%] Building CXX object Third-party/EasyBMP/CMakeFiles/EasyBMP.dir/source/EasyBMP.cpp.o
[  4%] Linking CXX static library libEasyBMP.a
[  4%] Built target EasyBMP
[  6%] Building CXX object Source/Coordinate/CMakeFiles/Coordinate.dir/GridCoordinate.cpp.o
[  8%] Linking CXX static library libCoordinate.a
[  8%] Built target Coordinate
[ 10%] Building CXX object Source/Layout/CMakeFiles/Layout.dir/YeeGridLayout.cpp.o
[ 12%] Building CXX object Source/Layout/CMakeFiles/Layout.dir/Approximation.cpp.o
[ 14%] Building CXX object Source/Layout/CMakeFiles/Layout.dir/ParallelYeeGridLayout.cpp.o
[ 16%] Linking CXX static library libLayout.a
[ 16%] Built target Layout
[ 18%] Building CXX object Source/Helpers/CMakeFiles/Helpers.dir/Assert.cpp.o
[ 20%] Linking CXX static library libHelpers.a
[ 20%] Built target Helpers
[ 22%] Building CXX object Source/Kernels/CMakeFiles/Kernels.dir/Kernels.cpp.o
[ 24%] Building CXX object Source/Kernels/CMakeFiles/Kernels.dir/FieldPoint.cpp.o
[ 26%] Linking CXX static library libKernels.a
[ 26%] Built target Kernels
[ 28%] Building CXX object Source/Settings/CMakeFiles/Settings.dir/Settings.cpp.o
[ 30%] Linking CXX static library libSettings.a
[ 30%] Built target Settings
[ 32%] Building CXX object Source/Grid/CMakeFiles/Grid.dir/ParallelBuffer2D.cpp.o
[ 34%] Building CXX object Source/Grid/CMakeFiles/Grid.dir/ParallelGrid.cpp.o
[ 36%] Building CXX object Source/Grid/CMakeFiles/Grid.dir/ParallelGrid2D.cpp.o
[ 38%] Building CXX object Source/Grid/CMakeFiles/Grid.dir/ParallelBuffer3D.cpp.o
[ 40%] Building CXX object Source/Grid/CMakeFiles/Grid.dir/ParallelGrid1D.cpp.o
[ 42%] Building CXX object Source/Grid/CMakeFiles/Grid.dir/ParallelGridCore.cpp.o
[ 44%] Building CXX object Source/Grid/CMakeFiles/Grid.dir/ParallelGrid3D.cpp.o
[ 46%] Building CXX object Source/Grid/CMakeFiles/Grid.dir/Grid.cpp.o
[ 48%] Linking CXX static library libGrid.a
[ 48%] Built target Grid
[ 51%] Building CXX object Source/Scheme/CMakeFiles/Scheme.dir/SchemeTMz.cpp.o
[ 53%] Building CXX object Source/Scheme/CMakeFiles/Scheme.dir/SchemeTEz.cpp.o
[ 55%] Building CXX object Source/Scheme/CMakeFiles/Scheme.dir/Scheme3D.cpp.o
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp: In member function ‘Scheme3D::NPair Scheme3D::ntffN_x(grid_coord, FPValue, FPValue, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*)’:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3526:32: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_teta (0.0, 0.0);
                                ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3527:31: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_phi (0.0, 0.0);
                               ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3560:50: error: expression list treated as compound expression in initializer [-fpermissive]
       FieldValue exponent (cos(k*arg), sin(k*arg));
                                                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp: In member function ‘Scheme3D::NPair Scheme3D::ntffN_y(grid_coord, FPValue, FPValue, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*)’:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3583:32: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_teta (0.0, 0.0);
                                ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3584:31: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_phi (0.0, 0.0);
                               ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3617:50: error: expression list treated as compound expression in initializer [-fpermissive]
       FieldValue exponent (cos(k*arg), sin(k*arg));
                                                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp: In member function ‘Scheme3D::NPair Scheme3D::ntffN_z(grid_coord, FPValue, FPValue, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*)’:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3640:32: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_teta (0.0, 0.0);
                                ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3641:31: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_phi (0.0, 0.0);
                               ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3674:50: error: expression list treated as compound expression in initializer [-fpermissive]
       FieldValue exponent (cos(k*arg), sin(k*arg));
                                                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp: In member function ‘Scheme3D::NPair Scheme3D::ntffL_x(grid_coord, FPValue, FPValue, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*)’:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3697:32: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_teta (0.0, 0.0);
                                ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3698:31: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_phi (0.0, 0.0);
                               ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3735:50: error: expression list treated as compound expression in initializer [-fpermissive]
       FieldValue exponent (cos(k*arg), sin(k*arg));
                                                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp: In member function ‘Scheme3D::NPair Scheme3D::ntffL_y(grid_coord, FPValue, FPValue, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*)’:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3757:32: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_teta (0.0, 0.0);
                                ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3758:31: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_phi (0.0, 0.0);
                               ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3795:50: error: expression list treated as compound expression in initializer [-fpermissive]
       FieldValue exponent (cos(k*arg), sin(k*arg));
                                                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp: In member function ‘Scheme3D::NPair Scheme3D::ntffL_z(grid_coord, FPValue, FPValue, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*)’:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3818:32: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_teta (0.0, 0.0);
                                ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3819:31: error: expression list treated as compound expression in initializer [-fpermissive]
   FieldValue sum_phi (0.0, 0.0);
                               ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3856:50: error: expression list treated as compound expression in initializer [-fpermissive]
       FieldValue exponent (cos(k*arg), sin(k*arg));
                                                  ^
In file included from /home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldPoint.h:4:0,
                 from /home/cem/Desktop/fdtd3d-master/Source/File-Management/BMPHelper.h:5,
                 from /home/cem/Desktop/fdtd3d-master/Source/File-Management/Dumper/BMPDumper.h:4,
                 from /home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:1:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp: In member function ‘FPValue Scheme3D::Pointing_scat(FPValue, FPValue, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*, Grid<GridCoordinate3DTemplate<long unsigned int> >*)’:
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3917:35: error: request for member ‘real’ in ‘first’, which is of non-class type ‘FieldValue {aka double}’
   FPValue first_abs2 = SQR (first.real ()) + SQR (first.imag ());
                                   ^
/home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldValue.h:72:18: note: in definition of macro ‘SQR’
 #define SQR(x) ((x) * (x))
                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3917:35: error: request for member ‘real’ in ‘first’, which is of non-class type ‘FieldValue {aka double}’
   FPValue first_abs2 = SQR (first.real ()) + SQR (first.imag ());
                                   ^
/home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldValue.h:72:24: note: in definition of macro ‘SQR’
 #define SQR(x) ((x) * (x))
                        ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3917:57: error: request for member ‘imag’ in ‘first’, which is of non-class type ‘FieldValue {aka double}’
   FPValue first_abs2 = SQR (first.real ()) + SQR (first.imag ());
                                                         ^
/home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldValue.h:72:18: note: in definition of macro ‘SQR’
 #define SQR(x) ((x) * (x))
                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3917:57: error: request for member ‘imag’ in ‘first’, which is of non-class type ‘FieldValue {aka double}’
   FPValue first_abs2 = SQR (first.real ()) + SQR (first.imag ());
                                                         ^
/home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldValue.h:72:24: note: in definition of macro ‘SQR’
 #define SQR(x) ((x) * (x))
                        ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3918:37: error: request for member ‘real’ in ‘second’, which is of non-class type ‘FieldValue {aka double}’
   FPValue second_abs2 = SQR (second.real ()) + SQR (second.imag ());
                                     ^
/home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldValue.h:72:18: note: in definition of macro ‘SQR’
 #define SQR(x) ((x) * (x))
                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3918:37: error: request for member ‘real’ in ‘second’, which is of non-class type ‘FieldValue {aka double}’
   FPValue second_abs2 = SQR (second.real ()) + SQR (second.imag ());
                                     ^
/home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldValue.h:72:24: note: in definition of macro ‘SQR’
 #define SQR(x) ((x) * (x))
                        ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3918:60: error: request for member ‘imag’ in ‘second’, which is of non-class type ‘FieldValue {aka double}’
   FPValue second_abs2 = SQR (second.real ()) + SQR (second.imag ());
                                                            ^
/home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldValue.h:72:18: note: in definition of macro ‘SQR’
 #define SQR(x) ((x) * (x))
                  ^
/home/cem/Desktop/fdtd3d-master/Source/Scheme/Scheme3D.cpp:3918:60: error: request for member ‘imag’ in ‘second’, which is of non-class type ‘FieldValue {aka double}’
   FPValue second_abs2 = SQR (second.real ()) + SQR (second.imag ());
                                                            ^
/home/cem/Desktop/fdtd3d-master/Source/Kernels/FieldValue.h:72:24: note: in definition of macro ‘SQR’
 #define SQR(x) ((x) * (x))
                        ^
Source/Scheme/CMakeFiles/Scheme.dir/build.make:110: recipe for target 'Source/Scheme/CMakeFiles/Scheme.dir/Scheme3D.cpp.o' failed
make[2]: *** [Source/Scheme/CMakeFiles/Scheme.dir/Scheme3D.cpp.o] Error 1
CMakeFiles/Makefile2:759: recipe for target 'Source/Scheme/CMakeFiles/Scheme.dir/all' failed
make[1]: *** [Source/Scheme/CMakeFiles/Scheme.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zer011b** [comment]
Fixed
