### ISSUE TITLE
3d runnning failed

### ISSUE THREAD

**Issue by EMinsight** [zer011b/fdtd3d#84]
I successed build fd3d with the command:
cmake .. -DCMAKE_BUILD_TYPE=Release -DVALUE_TYPE=d -DCOMPLEX_FIELD_VALUES=OFF -DTIME_STEPS=2 -DPARALLEL_GRID_DIMENSION=3 -DPRINT_MESSAGE=ON -DPARALLEL_GRID=ON -DPARALLEL_BUFFER_DIMENSION=xyz  -DCXX11_ENABLED=ON -DCUDA_ENABLED=OFF -DCUDA_ARCH_SM_TYPE=sm_50

1.There is a question confused me, what does -DTIME_STEPS mean?

2.But when I run it with MPI:
mpiexec -n 8 fd3d --3d

It shows:
Unreachable executed at /mnt/hgfs/linux_share/fdtd3d-master/Source/Scheme/Scheme3D.cpp:339.
backtrace () returned 5 addresses
./fdtd3d(_Z12program_failv+0x2b) [0x46833b]
./fdtd3d(_ZN8Scheme3DC2EP13YeeGridLayoutRK24GridCoordinate3DTemplateImEj+0xe0b) [0x4242cb]
./fdtd3d(main+0xc88) [0x40e458]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f035e1a1830]
./fdtd3d(_start+0x29) [0x40ed99]
Unreachable executed at /mnt/hgfs/linux_share/fdtd3d-master/Source/Scheme/Scheme3D.cpp:339.
backtrace () returned 5 addresses
./fdtd3d(_Z12program_failv+0x2b) [0x46833b]
./fdtd3d(_ZN8Scheme3DC2EP13YeeGridLayoutRK24GridCoordinate3DTemplateImEj+0xe0b) [0x4242cb]
./fdtd3d(main+0xc88) [0x40e458]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fde312cd830]
./fdtd3d(_start+0x29) [0x40ed99]
Unreachable executed at /mnt/hgfs/linux_share/fdtd3d-master/Source/Scheme/Scheme3D.cpp:339.
backtrace () returned 5 addresses
./fdtd3d(_Z12program_failv+0x2b) [0x46833b]
./fdtd3d(_ZN8Scheme3DC2EP13YeeGridLayoutRK24GridCoordinate3DTemplateImEj+0xe0b) [0x4242cb]
./fdtd3d(main+0xc88) [0x40e458]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f8e48bd1830]
./fdtd3d(_start+0x29) [0x40ed99]
Unreachable executed at /mnt/hgfs/linux_share/fdtd3d-master/Source/Scheme/Scheme3D.cpp:339.
backtrace () returned 5 addresses
./fdtd3d(_Z12program_failv+0x2b) [0x46833b]
./fdtd3d(_ZN8Scheme3DC2EP13YeeGridLayoutRK24GridCoordinate3DTemplateImEj+0xe0b) [0x4242cb]
./fdtd3d(main+0xc88) [0x40e458]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7faba5135830]
./fdtd3d(_start+0x29) [0x40ed99]
Unreachable executed at /mnt/hgfs/linux_share/fdtd3d-master/Source/Scheme/Scheme3D.cpp:339.
backtrace () returned 5 addresses
./fdtd3d(_Z12program_failv+0x2b) [0x46833b]
./fdtd3d(_ZN8Scheme3DC2EP13YeeGridLayoutRK24GridCoordinate3DTemplateImEj+0xe0b) [0x4242cb]
./fdtd3d(main+0xc88) [0x40e458]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f04f73ce830]
./fdtd3d(_start+0x29) [0x40ed99]
Unreachable executed at /mnt/hgfs/linux_share/fdtd3d-master/Source/Scheme/Scheme3D.cpp:339.
backtrace () returned 5 addresses
./fdtd3d(_Z12program_failv+0x2b) [0x46833b]
./fdtd3d(_ZN8Scheme3DC2EP13YeeGridLayoutRK24GridCoordinate3DTemplateImEj+0xe0b) [0x4242cb]
./fdtd3d(main+0xc88) [0x40e458]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f11047b1830]
./fdtd3d(_start+0x29) [0x40ed99]
Unreachable executed at /mnt/hgfs/linux_share/fdtd3d-master/Source/Scheme/Scheme3D.cpp:339.
backtrace () returned 5 addresses
./fdtd3d(_Z12program_failv+0x2b) [0x46833b]
./fdtd3d(_ZN8Scheme3DC2EP13YeeGridLayoutRK24GridCoordinate3DTemplateImEj+0xe0b) [0x4242cb]
./fdtd3d(main+0xc88) [0x40e458]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f622bff4830]
./fdtd3d(_start+0x29) [0x40ed99]
Unreachable executed at /mnt/hgfs/linux_share/fdtd3d-master/Source/Scheme/Scheme3D.cpp:339.
backtrace () returned 5 addresses
./fdtd3d(_Z12program_failv+0x2b) [0x46833b]
./fdtd3d(_ZN8Scheme3DC2EP13YeeGridLayoutRK24GridCoordinate3DTemplateImEj+0xe0b) [0x4242cb]
./fdtd3d(main+0xc88) [0x40e458]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f3b1acd8830]
./fdtd3d(_start+0x29) [0x40ed99]

**Comment by zer011b** [comment]
TIME_STEPS specify number of steps in time, which are stored in memory. The number of time steps required for computation does actually depend on the parameters of the computation, so this will be moved to runtime parameters in future. Currently this is set to available maximum by default (2 time steps).

**Comment by zer011b** [comment]
Fixed in #85
