### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by osad-dm** [zer011b/fdtd3d#97]
Hi, I would like to use your solver, but ran into a problem.
When I compiled the project from the Readme instructions, I got a lot of errors related to the compilation of the ShemeTEz and BMPDumper files, such as incorrect conversion to non-scalar type or no matching function for call. Could you help me? (Ubuntu 14.04.5 LTS(by Win) and Scientific 7.3)
Thank you.

**Comment by zer011b** [comment]
Could you post compilation commands, compilation output, version of compiler and commit hash?

Actually, 2D modes (TMz and TEz) are temporarily disabled. Currently, you could only use 3 mode, so, you could only specify `-DPARALLEL_GRID_DIMENSION=3` and pass `--3d` to command line. I'm currently working on unification of 1D, 2D and 3D modes.

**Comment by osad-dm** [comment]
Thank you! This works with --3d
